### ISSUE TITLE
QUESTION: How do I change my environments domain name?

### ISSUE THREAD

**Issue by abeachcatalyze** [catalyzeio/paas-faq#14]
Please contact Catalyze [support](https://catalyzeio.zendesk.com/hc/en-us/requests/new) with the details of the new domain name.  We will need a SSL certificate that matches the domain name.  There are many providers of SSL certificates.  We will need to know the domain name and if the SSL certificate for the domain name will be a wildcard certificate.  Someone from Catalyze will contact you so we can coordinate a schedule to make the change and establish a secure method of sharing the new certificate files.

**Comment by rr1000** [comment]
Added to domains.md
