### ISSUE TITLE
QUESTION: Can I have multiple domain names for an environment ?

### ISSUE THREAD

**Issue by abeachcatalyze** [catalyzeio/paas-faq#17]
Yes, when configuring a new environment, you can add a domain name and SSL certificate with the Catalyze Dashboard.  

If your environment is already configured, deployed and running please contact Catalyze support.  We will need to know the domain name and if the SSL certificate for the domain name will be a wildcard certificate. Someone from Catalyze will contact you so we can coordinate a schedule to make the change and establish a secure method of sharing the new certificate files.

**Comment by rr1000** [comment]
Added to domains.md
