### ISSUE TITLE
QUESTION: How do I contact Catalyze support?

### ISSUE THREAD

**Issue by abeachcatalyze** [catalyzeio/paas-faq#18]
Contact Catalyze Support by using this [form](https://catalyzeio.zendesk.com/hc/en-us/requests/new).  For requests regarding PaaS, please include your environment id. You can find the environment id in the url of the Dashboard for your environment.  You can also find the environment id when using the [paas-cli ](https://github.com/catalyzeio/catalyze-paas-cli) with the command `catalyze environments`

In addition, please review the Response-Times section of our [Service Agreement](https://legal.catalyze.io/#4-4-response-times)

```Catalyze shall provide Customer support, which shall be available Monday through Friday, 7:00 a.m. To 5:00 p.m. Central time, excluding holidays.```

**Comment by rr1000** [comment]
added to contact.md (Contact and Notifications)
