### ISSUE TITLE
Question:  I have a database bastion service.  How do I connect to the DB bastion ?

### ISSUE THREAD

**Issue by abeachcatalyze** [catalyzeio/paas-faq#19]
When your database bastion service was configured and deployed, you should have received a message from Catlayze Support that informed you have the user name and ssh key that should be used to connect to the service.

Use a ssh client, such as openssh or putty to remotely connect to the database client application.

To connect with openssh, enter the ssh command in the format  `ssh -i <identify file> <user>@<ip address>`.  For example `ssh -i /home/fred/mykeys/catalyze.key fred@104.101.102.103`

**Comment by rr1000** [comment]
Added to databases.md
