### ISSUE TITLE
Question: Can I get alerts about my environment ?

### ISSUE THREAD

**Issue by abeachcatalyze** [catalyzeio/paas-faq#20]
Each paas environment comes with a Monitoring dashboard. Please see the [Accessing Monitoring](https://resources.catalyze.io/paas/getting-started/accessing-your-environment/accessing-monitoring/) section of our Resources page for more information regarding Monitoring.  We are working on a solution that will allow you to be notified when events occur.  Currently, you can subscribe an email address to be notified when an application build and redeployment has been completed.

**Comment by rr1000** [comment]
Added to contact.md (Contact and Notifications)
