### ISSUE TITLE
Question: How do I add another user to my environment

### ISSUE THREAD

**Issue by uphoff** [catalyzeio/paas-faq#23]
Our command line interface (CLI) is used to add users to an environment via the [adduser command](https://resources.catalyze.io/paas/cli/sections/adduser/). 

If you have not set up the CLI yet you'll need to get it set up by following the instructions provided here: https://github.com/catalyzeio/catalyze-paas-cli. Make sure you have associated the correct environment with the CLI before continuing. 

Next, you'll need to know the user ID for each user you are looking to add to the environment. They'll need to sign up for a [dashboard](https://dashboard.catalyze.io) account and activate their account via email validation. Then have each user run `catalyze whoami`, which will output the user ID.
We will be adding a feature to the Dashboard in the future that will display the user ID. 

Once you have all the user IDs just run `catalyze adduser <userid>` for each user ID. The users should now see the environment in their list of environments.

**Comment by anthonypleshek** [comment]
This is done: https://resources.catalyze.io/paas/paas-faq/manage-users/
