### ISSUE TITLE
Can I have a VPN to my Paas environment?

### ISSUE THREAD

**Issue by abeachcatalyze** [catalyzeio/paas-faq#24]
~~All interaction with your Paas environment should be done with the [Catalyze Dashboard](https://dashboard.catalyze.io), Catalyze [paas-cli](https://github.com/catalyzeio/catalyze-paas-cli) client application or your application code.~~

**Comment by uphoff** [comment]
We do not support the ability to connect to PaaS environments via VPN. We are able to configure secure console access via SSH to meet certain use cases. This service requires an additional monthly charge. Please [contact us](https://catalyzeio.zendesk.com/hc/en-us/requests/new) for details. 

Beyond that, all interaction with your PaaS environment should be done with the [Catalyze Dashboard](https://dashboard.catalyze.io), Catalyze [paas-cli](https://github.com/catalyzeio/catalyze-paas-cli) client application or your application code.
