### ISSUE TITLE
Can I use MySQL workbench or my other favorite database GUI ?

### ISSUE THREAD

**Issue by abeachcatalyze** [catalyzeio/paas-faq#25]
~~The catalyze paas-cli provides some database management access such as database backup and restoration. Please see our paas-cli [Resources page](https://resources.catalyze.io/paas/cli/) We are working on a feature to provide additional capability to the paas-cli that will provide you with more management access to your database.~~

**Comment by uphoff** [comment]
For security reasons we do not allow direct connections from the Internet to the database within your environment. All database access is restricted to the application node(s) and database replicas for High Availability databases. 

We are working on a feature to provide additional capability to the paas-cli that will provide you with more management access to your database via the command line tools for each database (e.g. psql, mysql, redis-cli). That feature will be available in the third quarter of 2015.
