### ISSUE TITLE
Are any metrics available for my Paas environment ?

### ISSUE THREAD

**Issue by abeachcatalyze** [catalyzeio/paas-faq#28]
~~We are currently working on a solution that will provide access to the metrics used by your Paas environment through the paas-cli.~~

**Comment by uphoff** [comment]
We are currently working on a solution that will provide access to the metrics used by your PaaS environment through the CLI and the dashboard. This feature is in beta and will be available to all users via the CLI by mid-Summer 2015. Dashboard integration will follow soon after. 

To get a preview of the type of metrics we are collecting, have a look at our [cadvisor-metrics](https://github.com/catalyzeio/cadvisor-metrics) repository, which we wrote specifically for this purpose and have released as open source software.
