### ISSUE TITLE
QUESTION: How does Catalyze do background processing (workers)?

### ISSUE THREAD

**Issue by rr1000** [catalyzeio/paas-faq#3]
- [ ] How does Catalyze do background processing (overview)
- [ ] How does a user gain access?

**Comment by abeachcatalyze** [comment]
There are two types of background processing, rake tasks and workers.  You can deploy a number of worker processes up the to amount that have been contracted.  Workers are intended to be for longer running processes.  Rake tasks are intended for single short running tasks and are available when using a rails framework.

Worker processes are executed with the paas-cli.  The worker process is defined in a Procfile

Example worker Procfile:

```
web: bundle exec unicorn -p $PORT -c ./config/unicorn.rb
myworker: bundle exec sidekiq
```

This example, from a [ruby-rails-sample](https://github.com/nateradtke/ruby-rails-sample) application starts sidekiq in a worker process.

The worker is then started with the paas cli command `catalyze worker <Procfile target>`

For example:
```catalyze worker myworker```

Please see the [paas cli reference](https://resources.catalyze.io/paas/cli/sections/worker/) for more information about using workers with the paas-cli.

The worker process will have access to your datasources (database servers and cache servers).  The worker process will have access to the same environment variables as the application service.

The worker process does not have a user interface.  You can view the status and information from a worker with the Catalyze logging dashboard.

**Comment by nateradtke** [comment]
Pulled in above content to the FAQ article answering the above questions. See PR tagged above.
