### ISSUE TITLE
QUESTION: Do I have access to Cloud Storage?

### ISSUE THREAD

**Issue by rr1000** [catalyzeio/paas-faq#4]
- Explain what Cloud Storage means to us (space used by your app and database)
- Will Catalyze ever offer actual Cloud Storage?

**Comment by uphoff** [comment]
As part of your Catalyze environment you have a fixed amount of "Cloud Storage" space that includes your application's assets (the application code/binaries, static JavaScript, HTML, CSS) as well as disk space used by your database instance. This is not the same as a cloud-based file storage or CDN solution like Rackspace's Cloud Files or AWS S3. We have the ability to configure a compliant S3 bucket as part of you environment at an additional charge. This is our preferred approach, as opposed to storing content like large images and PDFs in your git repository (which is considered bad practice by most) and then serving them up via your application.
