### ISSUE TITLE
QUESTION: How can I add multiple users to my environment?

### ISSUE THREAD

**Issue by rr1000** [catalyzeio/paas-faq#6]
We are currently working on implementing functionality into the dashboard that will allow users to easily add other users to their environment(s). For now we request that you have your users create individual catalyze accounts (https://preview.catalyze.io/signup). Once that's done you can file a support ticket with their usernames and the environments that you'd like to add them to and we'll add them for you.

**Comment by uphoff** [comment]
Might want to remove this in favor of #23.

**Comment by anthonypleshek** [comment]
#23 is done, closing this one too

https://resources.catalyze.io/paas/paas-faq/manage-users/
