### ISSUE TITLE
What is HA?

### ISSUE THREAD

**Issue by rr1000** [catalyzeio/paas-faq#8]
- [ ] What is HA?
- [ ] Do I need HA to be HIPAA Compliant?
- [ ] Can I add HA after deployment?
- [ ] Is HA different than code scaling?

**Comment by abeachcatalyze** [comment]
What is HA?
A HA service means a service is Highly Available.   A service is highly available when there is a mechanism in place to detect when a service component is unavailable and restore the service.  Catalyze provides HA services by providing redundant components and the ability to quickly restore a service component. 

Catalyze provides HA data source and application services for a Paas environment by adding additional nodes for applications and data sources (servers such as databases and caching servers ) when a HA configuration is requested by  a customer. 

High Availability is not a requirement  to be HIPAA Compliant. 

HA components can be added after an environment is deployed.  Your application code may need to be changed to handle HA services.  The type of code change of course will depend on the type of service and the code platform.   Please contact Catalyze Support for assistance with adding HA services to your environment.

Code scaling is increasing a system's ability to handle a growing work load.  As the work of a system increases a system with a scaling method should be able to grow to handle the load.  Code scaling often means adding additional application servers to a service to handle increased demand.

**Comment by nateradtke** [comment]
Pulled in the content above to answer the proposed questions. See tagged PR.
